git:
  depth: false
language: java
jdk: oraclejdk11

before_install:
  - scripts/install-aws-cli.sh
  - scripts/configure-aws-profile.sh

script:
    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./gradlew prTest; fi'
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./gradlew test; fi'

after_success:
  - "./gradlew jacocoTestReport"
  - bash <(curl -s https://codecov.io/bash)
